name: Test

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Dockerfile
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./tests/Dockerfile
        load: true
        tags: mgnify-cobs-genome-search-tests

    - name: Run tests
      run: docker run -t mgnify-cobs-genome-search-tests
